### ISSUE TITLE
LICENSE.md file

### ISSUE THREAD

**Issue by Snosixtyboo** [ashawkey/diff-gaussian-rasterization#1]
Hi ashawkey,

thanks for the creative work and contributions to the base project! To keep everything correct, please kindly merge the LICENSE.md file from the source repo, or alternatively just ```git add``` it to yours!

Best and thanks,
Bernhard

**Comment by ashawkey** [comment]
@Snosixtyboo Thanks for the reminding! I have merged the original license in https://github.com/ashawkey/diff-gaussian-rasterization/commit/0e08f981abe4ada0c8bc7f8ab6eac9503a5f6b31.

**Comment by Snosixtyboo** [comment]
Great, thanks!
