### ISSUE TITLE
Render Normal Map

### ISSUE THREAD

**Issue by chensjtu** [ashawkey/diff-gaussian-rasterization#11]
Thanks for this wonderful repo! I wonder if you can support normal map rendering. Since normal map can show more details.

**Comment by Reed-yang** [comment]
> Thanks for this wonderful repo! I wonder if you can support normal map rendering. Since normal map can show more details.

Hi chensjtu! Did you find a released gaussian-rasterization that supports normal map rendering? thx in advance!

**Comment by slothfulxtx** [comment]
Hello, everyone, we implement a diff-gauss-rasterization repo which supports more than alpha, depth, normal maps rendering. You can find our code here https://github.com/slothfulxtx/diff-gaussian-rasterization

**Comment by chensjtu** [comment]
Many thanks for this wonderful implementation!
