### ISSUE TITLE
what are possible application and use of rendered_depth & rendered_alpha?

### ISSUE THREAD

**Issue by pknmax** [ashawkey/diff-gaussian-rasterization#18]
1. does this make trained scene representation/rendering better than original 3DGS rasterizer?
2. is there a way to use this to make loss term used in 3DGS more efficient and better?

**Comment by ansj11** [comment]
it is useful to use rendered_alpha to calculate mask loss in some object reconstruction cases. rendered_depth can also provide some guidance e.g. depth loss between rendered_depth and monocular depth.
