### ISSUE TITLE
zero123.ckpt to Diffusers Format?

### ISSUE THREAD

**Issue by JaeLee18** [ashawkey/diff-gaussian-rasterization#2]
This is amazing work!
Could you tell me how did you convert zero123.ckpt to Diffusers Format?
I tried their [script](https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py) but I got  `ValueError: Trying to set a tensor of shape torch.Size([320, 8, 3, 3]) in "weight" (which has shape torch.Size([320, 4, 3, 3])), this look incorrect.`

**Comment by ashawkey** [comment]
@JaeLee18 Hi, I use the script from threestudio: https://github.com/threestudio-project/threestudio/blob/main/scripts/convert_zero123_to_diffusers.py

**Comment by JaeLee18** [comment]
Thanks! It worked :)
