### ISSUE TITLE
Q about debug:)

### ISSUE THREAD

**Issue by TwiceMao** [ashawkey/diff-gaussian-rasterization#3]
I would like to ask you how to debug the diff-gaussian-rasterization project. Because I tried to enter the **_rasterizer_** by vscode on the original 3D-Gaussian codes, but couldn't. But I want to know some operating conditions and details of some codes of the diff-gaussian-rasterization project, so I need to debug it. Hope to get your help, thank you.

**Comment by ashawkey** [comment]
@TwiceMao Hi, you can try using `printf` inside cuda kernels, or `std::cout` in cpu part code. Note that you need to recompile every time to make the printing work.

**Comment by TwiceMao** [comment]
Okay, this is a very primitive approach. I would like to know if there is a method similar to debugging in VSCODE? For example, when I was running the DreamGaussian code, it called the Diff-rasterizer code.




毛懋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ashawkey/diff-gaussian-rasterization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月4日(星期三) 晚上6:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ashawkey/diff-gaussian-rasterization] Q about debug:) (Issue #3)





 
@TwiceMao Hi, you can try using printf inside cuda kernels, or std::cout in cpu part code. Note that you need to recompile every time to make the printing work.

**Comment by ashawkey** [comment]
well, sorry that I don't know a more convenient way...
