### ISSUE TITLE
Bug in depth backward

### ISSUE THREAD

**Issue by yihua7** [ashawkey/diff-gaussian-rasterization#4]
There exists a bug of lacking a parentheses [here](https://github.com/ashawkey/diff-gaussian-rasterization/blob/30be14209ca8d393bb75aac4c083f678ad8eae71/cuda_rasterizer/backward.cu#L459), referring to the [issue](https://github.com/graphdeco-inria/gaussian-splatting/pull/30#issuecomment-1740075269).
The backward of depth estimation may encounter CUDA error based on the current codes.

**Comment by ashawkey** [comment]
@yihua7 Thanks for spotting this! I have fixed it in https://github.com/ashawkey/diff-gaussian-rasterization/commit/d2109176d15619b2efcb4741bcf672bedba84fb2.

**Comment by yihua7** [comment]
Sure :)
By the way, I really appreciate your excellent projects. Based on torch-ngp I developed my SIGGRAPH paper [NeRF-Texture](https://github.com/yihua7/NeRF-Texture). I have acknowledged it on the website. 
Looking forward to your future works and learning more from you :)

**Comment by ashawkey** [comment]
Nice work! Thanks!
