### ISSUE TITLE
About alpha rendering.

### ISSUE THREAD

**Issue by zyhbili** [ashawkey/diff-gaussian-rasterization#5]
Nice implementation! 
I produce poor results when incorperating the alpha loss into multi-view reconstruction setting. Specifically, i use the ground-truth mask as a supervision. Intuitively, it would suppress the unreasonable gaussians outside of the object, but it produce more noisy  gaussians intead. I try adjusting the threshold of densifying and pruning, but it doesn't work. 
Could you offer some instructions？

**Comment by ashawkey** [comment]
@zyhbili Hi, we fixed a bug related to alpha loss, could you try with the latest code again?

**Comment by zyhbili** [comment]
Thanks a lot! It works for me.
